server:
  port: 8671
spring:
  application:
    name: eurekaserver
eureka:
  instance:
    hostname: 27.0.0.1
  client:
    serviceUrl:
      defaultZone: http://user:user123@127.0.0.1:8672/eureka/

security:
  basic:
    enabled: true
  user:
    name: admin
    password: admin123
